ALTER TYPE "FieldType" ADD VALUE 'RESIDENT_LOCATION_FAX';
ALTER TYPE "FieldType" ADD VALUE 'RESIDENT_LOCATION_LICENSING';
ALTER TYPE "FieldType" ADD VALUE 'RESIDENT_LOCATION_LICENSING_NAME';
ALTER TYPE "FieldType" ADD VALUE 'RESIDENT_LOCATION_ADMINISTRATOR_NAME';
ALTER TYPE "FieldType" ADD VALUE 'RESIDENT_LOCATION_ADMINISTRATOR_PHONE';
