def branchConfig = [
    'main'        : ['production' , 'cd_production', 'rise.caringdata.com'],
    'staging'     : ['staging'    , 'cd_staging'   , 'staging.caringdata.com'],
    'development' : ['development', 'cd_development', 'caringdata.at.services']
]

def config = branchConfig[env.BRANCH_NAME] ?: branchConfig['development']
def (DEPLOY_ENV, AGENT_LABEL, DOMAIN_NAME) = config

pipeline {
    agent { label "${AGENT_LABEL}" }

    environment {
        APP_NAME = 'cd-documenso'
        COMPOSE_PROJECT_NAME = "${APP_NAME}-${DEPLOY_ENV}"
        NODE_ENV = "${DEPLOY_ENV}"

        HEALTH_CHECK_RETRIES = 10
        HEALTH_CHECK_INTERVAL = 10
    }


    stages {
        stage('1. Init') {
            steps {
                script {
                    if (!DOMAIN_NAME) error("❌ No domain configured for branch ${env.BRANCH_NAME}")

                    currentBuild.displayName = "#${BUILD_NUMBER} - ${DEPLOY_ENV}"
                    echo """
                    🚀 DEPLOY INITIATED
                    -------------------
                    Env:    ${DEPLOY_ENV}
                    Files:  ${env.COMPOSE_FILES}
                    Agent:  ${AGENT_LABEL}
                    -------------------
                    """
                }
            }
        }
    }
}