declare namespace NodeJS {
  export interface ProcessEnv {
    PORT?: string;
    NEXT_PUBLIC_WEBAPP_URL?: string;

    NEXT_PRIVATE_DATABASE_URL: string;
    NEXT_PRIVATE_ENCRYPTION_KEY: string;
    NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: string;

    NEXT_PRIVATE_LOGGER_FILE_PATH?: string;

    NEXT_PUBLIC_UPLOAD_TRANSPORT?: 'database' | 's3';
    NEXT_PRIVATE_UPLOAD_ENDPOINT?: string;
    NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE?: string;
    NEXT_PRIVATE_UPLOAD_REGION?: string;
    NEXT_PRIVATE_UPLOAD_BUCKET?: string;
    NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID?: string;
    NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY?: string;
    NEXT_PRIVATE_UPLOAD_DISTRIBUTION_DOMAIN?: string;
    NEXT_PRIVATE_UPLOAD_DISTRIBUTION_KEY_ID?: string;
    NEXT_PRIVATE_UPLOAD_DISTRIBUTION_KEY_CONTENTS?: string;

    NEXT_PRIVATE_SIGNING_TRANSPORT?: 'local' | 'http' | 'gcloud-hsm';
    NEXT_PRIVATE_SIGNING_PASSPHRASE?: string;
    NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH?: string;
    NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS?: string;
    NEXT_PRIVATE_SIGNING_LOCAL_FILE_ENCODING?: string;
    NEXT_PRIVATE_SIGNING_GCLOUD_HSM_KEY_PATH?: string;
    NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_PATH?: string;
    NEXT_PRIVATE_SIGNING_GCLOUD_HSM_PUBLIC_CRT_FILE_CONTENTS?: string;
    NEXT_PRIVATE_SIGNING_GCLOUD_APPLICATION_CREDENTIALS_CONTENTS?: string;

    NEXT_PRIVATE_NOTIFY_EMAIL?: string;
    NEXT_PRIVATE_NOTIFY_PASSWORD?: string;
    NEXT_PRIVATE_NOTIFY_ENDPOINT?: string;

    NEXT_PUBLIC_DISABLE_SIGNUP?: string;

    NEXT_PRIVATE_API_KEY?: string;

    NEXT_PRIVATE_BROWSERLESS_URL?: string;

    NEXT_PRIVATE_JOBS_PROVIDER?: 'inngest' | 'local';

    NEXT_PUBLIC_USE_INTERNAL_URL_BROWSERLESS?: string;

    /**
     * Caring Data API integration
     */
    NEXT_PUBLIC_CD_SERVICE_URL?: string;
    NEXT_PUBLIC_CD_SERVICE_API_KEY?: string;

    /**
     * Inngest environment variables
     */
    INNGEST_EVENT_KEY?: string;
    NEXT_PRIVATE_INNGEST_APP_ID?: string;
    NEXT_PRIVATE_INNGEST_EVENT_KEY?: string;

    POSTGRES_URL?: string;
    DATABASE_URL?: string;
    POSTGRES_PRISMA_URL?: string;
    POSTGRES_URL_NON_POOLING?: string;

    /**
     * Google Vertex AI environment variables
     */
    GOOGLE_VERTEX_PROJECT_ID?: string;
    GOOGLE_VERTEX_LOCATION?: string;
    GOOGLE_VERTEX_API_KEY?: string;
  }
}
